CREATE TABLE 'people_and_places' (
	'id' INT NOT NULL AUTO_INCREMENT,
	'city' VARCHAR(80) DEFAULT NULL,
	'county' VARCHAR(80) DEFAULT NULL,
	'country' VARCHAR(80) DEFAULT NULL,
	'given_name' VARCHAR(80) DEFAULT NULL,
	'family_name' VARCHAR(80) DEFAULT NULL,
	'date_of_birth' DATE DEFAULT NULL,
	PRIMARY KEY ('id')
);